require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImportantDatesController do

  # This should return the minimal set of attributes required to create a valid
  # ImportantDate. As you add validations to ImportantDate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date" => "2013-05-15" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ImportantDatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all important_dates as @important_dates" do
      important_date = ImportantDate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:important_dates).should eq([important_date])
    end
  end

  describe "GET show" do
    it "assigns the requested important_date as @important_date" do
      important_date = ImportantDate.create! valid_attributes
      get :show, {:id => important_date.to_param}, valid_session
      assigns(:important_date).should eq(important_date)
    end
  end

  describe "GET new" do
    it "assigns a new important_date as @important_date" do
      get :new, {}, valid_session
      assigns(:important_date).should be_a_new(ImportantDate)
    end
  end

  describe "GET edit" do
    it "assigns the requested important_date as @important_date" do
      important_date = ImportantDate.create! valid_attributes
      get :edit, {:id => important_date.to_param}, valid_session
      assigns(:important_date).should eq(important_date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ImportantDate" do
        expect {
          post :create, {:important_date => valid_attributes}, valid_session
        }.to change(ImportantDate, :count).by(1)
      end

      it "assigns a newly created important_date as @important_date" do
        post :create, {:important_date => valid_attributes}, valid_session
        assigns(:important_date).should be_a(ImportantDate)
        assigns(:important_date).should be_persisted
      end

      it "redirects to the created important_date" do
        post :create, {:important_date => valid_attributes}, valid_session
        response.should redirect_to(ImportantDate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved important_date as @important_date" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImportantDate.any_instance.stub(:save).and_return(false)
        post :create, {:important_date => { "date" => "invalid value" }}, valid_session
        assigns(:important_date).should be_a_new(ImportantDate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImportantDate.any_instance.stub(:save).and_return(false)
        post :create, {:important_date => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested important_date" do
        important_date = ImportantDate.create! valid_attributes
        # Assuming there are no other important_dates in the database, this
        # specifies that the ImportantDate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ImportantDate.any_instance.should_receive(:update_attributes).with({ "date" => "2013-05-15" })
        put :update, {:id => important_date.to_param, :important_date => { "date" => "2013-05-15" }}, valid_session
      end

      it "assigns the requested important_date as @important_date" do
        important_date = ImportantDate.create! valid_attributes
        put :update, {:id => important_date.to_param, :important_date => valid_attributes}, valid_session
        assigns(:important_date).should eq(important_date)
      end

      it "redirects to the important_date" do
        important_date = ImportantDate.create! valid_attributes
        put :update, {:id => important_date.to_param, :important_date => valid_attributes}, valid_session
        response.should redirect_to(important_date)
      end
    end

    describe "with invalid params" do
      it "assigns the important_date as @important_date" do
        important_date = ImportantDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImportantDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => important_date.to_param, :important_date => { "date" => "invalid value" }}, valid_session
        assigns(:important_date).should eq(important_date)
      end

      it "re-renders the 'edit' template" do
        important_date = ImportantDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImportantDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => important_date.to_param, :important_date => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested important_date" do
      important_date = ImportantDate.create! valid_attributes
      expect {
        delete :destroy, {:id => important_date.to_param}, valid_session
      }.to change(ImportantDate, :count).by(-1)
    end

    it "redirects to the important_dates list" do
      important_date = ImportantDate.create! valid_attributes
      delete :destroy, {:id => important_date.to_param}, valid_session
      response.should redirect_to(important_dates_url)
    end
  end

end
